# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e53a1d1351ef7cd7ecce73e81806d4ca0fe9d4668aa330e2609fcfffac1c90742ca8a40c4e7800c69b2245b2603cbe1eb6a4622c5d8ca3ea40fca6bbe203bde0

test:
  secret_key_base: 2aad1acab6cb328fd0acf84479a4c1069f6d9260ad39e9ede1bd029ef0895e1e77e888014642ec1ffe262ca1ef2b0a58ba824da32bae3e7b3197b4c54979df60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
